version: "3.6"

services:
  9light:
    build: .
    container_name: 9light
    restart: always
    environment:
      - LOG_LEVEL=DEBUG
      - VERSION=${VERSION-unknown}
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/gpiomem
    privileged: true
