version: "3"

services:
  HomeOfficeLight:
    build: .
    restart: always
    environment:
      - LOG_LEVEL=DEBUG
      - GIT_VERSION=${GIT_VERSION-unknown}
    ports:
      - 9000:9000
      - 9080:9080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/gpiomem
    privileged: true
